// <auto-generated />
using System;
using GymTrackerDataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTrackerDataModel.Migrations
{
    [DbContext(typeof(EntityDBContext))]
    [Migration("20260529110418_initialClean")]
    partial class initialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymTrackerDataModel.Models.DOWWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TemplateWorkoutId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WorkoutPeriodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateWorkoutId");

                    b.HasIndex("WorkoutPeriodId");

                    b.ToTable("TRN_DOWWorkout");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StepsToPerform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("LKP_Exercise", (string)null);
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.ExerciseMetric", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("MetricId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("ExerciseId", "MetricId");

                    b.HasIndex("MetricId");

                    b.ToTable("LKP_ExerciseMetric", (string)null);
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.ExerciseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("LKP_ExerciseType", (string)null);
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LKP_Metric");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("LKP_TemplateExercise", (string)null);
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TemplateExerciseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateExerciseId", "Order")
                        .IsUnique();

                    b.ToTable("LKP_TemplateSet", (string)null);
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateSetMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MetricId")
                        .HasColumnType("int");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TemplateSetId")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MetricId");

                    b.HasIndex("TemplateSetId");

                    b.ToTable("LKP_TemplateSetMetric", (string)null);
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LKP_WorkoutTemplate", (string)null);
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.WorkoutPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("LKP_WorkoutPeriod");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.DOWWorkout", b =>
                {
                    b.HasOne("GymTrackerDataModel.Models.TemplateWorkout", "TemplateWorkout")
                        .WithMany()
                        .HasForeignKey("TemplateWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackerDataModel.Models.WorkoutPeriod", "WorkoutPeriod")
                        .WithMany()
                        .HasForeignKey("WorkoutPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateWorkout");

                    b.Navigation("WorkoutPeriod");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.Exercise", b =>
                {
                    b.HasOne("GymTrackerDataModel.Models.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.ExerciseMetric", b =>
                {
                    b.HasOne("GymTrackerDataModel.Models.Exercise", "Exercise")
                        .WithMany("ExerciseMetrics")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackerDataModel.Models.Metric", "Metric")
                        .WithMany("ExerciseMetrics")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateExercise", b =>
                {
                    b.HasOne("GymTrackerDataModel.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackerDataModel.Models.TemplateWorkout", "WorkoutTemplate")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateSet", b =>
                {
                    b.HasOne("GymTrackerDataModel.Models.TemplateExercise", "TemplateExercise")
                        .WithMany("TemplateSets")
                        .HasForeignKey("TemplateExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateExercise");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateSetMetric", b =>
                {
                    b.HasOne("GymTrackerDataModel.Models.Metric", "Metric")
                        .WithMany("TemplateSetMetrics")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrackerDataModel.Models.TemplateSet", "TemplateSet")
                        .WithMany("TemplateSetMetrics")
                        .HasForeignKey("TemplateSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");

                    b.Navigation("TemplateSet");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseMetrics");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.Metric", b =>
                {
                    b.Navigation("ExerciseMetrics");

                    b.Navigation("TemplateSetMetrics");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateExercise", b =>
                {
                    b.Navigation("TemplateSets");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateSet", b =>
                {
                    b.Navigation("TemplateSetMetrics");
                });

            modelBuilder.Entity("GymTrackerDataModel.Models.TemplateWorkout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
